### PR TITLE
fix: fix test on develop

### PR DESCRIPTION
**Pull request by eburgos**
truffle test was showing a failed test.
A test was relying on a time based delay to wait for some notifications to fire.
Added a callback wrapper to the original callback so that it counts the amount of notifications and resolves a promise.

### CODE REVIEW

**Review by satello — APPROVED** [review]
Thanks for the PR @eburgos. This looks like it will fix that problem nicely. I will see what is going on with coveralls

**Comment by epiqueras** [comment]
@satello 
@eburgos 
Travis does not allow external branches to access ENV VARS. 
In `.travis.yml`, change

```sh
- 'yarn run test:coveralls'
```

to

```sh
- 'if [ -n "$COVERALLS_REPO_TOKEN" ]; then yarn run test:coveralls; fi'
```

**Comment by epiqueras** [comment]
@eburgos 
@satello 
I just fixed it.

Rebase onto `develop` and you should be good to go.

**Comment by eburgos** [comment]
oops sorry enrique just saw this U_U

**Comment by epiqueras** [comment]
@eburgos Nice work!

**Pull request merged**
